spring:
  data:
    redis:
      host: 47.97.30.247
      port: 6379
      password: 12345678s
      database: 2
      connect-timeout: 1000
      jedis:
        pool:
          enabled: true
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0


de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.4.18
        database-dir: target/embedded-mongo
