spring:
  data:
    redis:
      host: 47.97.30.247
      port: 6379
      password: 12345678s
      database: 2
      connect-timeout: 1000
      jedis:
        pool:
          enabled: true
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0


    mongodb:
      #      uri: mongodb://localhost/personkit
      uri: mongodb://admin:123456@10.168.1.115/admin
  mongodb:
    embedded:
      storage:
        database-dir: ./mongo
      version: 3.5.5
